### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by benjamingr** [toranome/mht-extract#1]
Hey,

I wrote a package that does something similar over at https://www.npmjs.com/package/fast-mhtml 

Biggest difference in regards to images is the usage of the 64 library and handling non-base64 encoded images.

Let me know if you want to collaborate or if you want to try using the functionality out of fast-mhtml in this one (decoder.js for example)

**Comment by torazem** [comment]
Hey!

I'm a year and a half late 😱 sorry! I suspect I let my notifications get too noisy and just didn't see this.

This repo is was a one-off experiment that served its limited purpose; I will add a deprecation notice to the readme shortly.

Thank you for the interest! I'll try `fast-mhtml` next time I need this functionality
